const CONFLICT_CODE = 409;
const FORBIDDEN_CODE = 403;
const VALIDATION_CODE = 400;
const UNAUTHORIZED_CODE = 401;
const NOT_FOUND_CODE = 404;

module.exports = {
  VALIDATION_CODE,
  UNAUTHORIZED_CODE,
  FORBIDDEN_CODE,
  NOT_FOUND_CODE,
  CONFLICT_CODE,
};
